### ISSUE TITLE
Feature request: option to set headers to be not sticky

### ISSUE THREAD

**Issue by vovan888** [eowise/recyclerview-stickyheaders#12]

**Comment by oinegue** [comment]
Setting `.setSticky(false)` doesn't work in my app, neither in the sample app.
The header stay sticked on top and disappear when the first item of the group goes away from the top of the screen. Quite strange...
I would like this feature as well. 
By the way, great job with this library!

**Comment by acatinon** [comment]
I've just tested non sticky headers with the samples, and it works... There is the code I have changed :

```java
        top = new StickyHeadersBuilder()
                .setAdapter(personAdapter)
                .setRecyclerView(list)
                .setStickyHeadersAdapter(new BigramHeaderAdapter(personDataProvider.getItems()))
                .setOnHeaderClickListener(this)
                .setSticky(false) \\ Adde this line
                .build();
```

Can you provide a non working sample ?

**Comment by oinegue** [comment]
Yes, I tried exactly that code on the sample app, cloned yesterday from github. And something doesn't work.
Here is a gif of the behaviour.
I'm testing on a Galaxy Note 3 with Android 4.4.2
![sticky_optim](https://cloud.githubusercontent.com/assets/3747027/5748064/3c337aec-9c3d-11e4-93aa-1c2fb547e559.gif)

**Comment by acatinon** [comment]
Ok, the [commit](49d8a5a937d0251b4119c708fcc83cba852b1951) I pushed few minutes ago fixes this issue too.

Can you try with the latest sources ?

**Comment by oinegue** [comment]
Yes, it fixes the issue!
Thank you @acatinon!
