### ISSUE TITLE
Sometimes header do not push header on top of them when reaching the top of the views.

### ISSUE THREAD

**Issue by vincentbrison** [eowise/recyclerview-stickyheaders#25]
Hi,
Sometimes, when a header reach the top of the view (when scrolling down in a list for example), the header do not replace the one above him, but instead is drawn under the current top header. When the "future" top header reach totally the top of the view, it is finally correctly draw above the old header at top.

What could occurs is that the "old" top header is not always correctly animated ?

If needed, I can provide a sample project.

**Comment by xGary** [comment]
I am having a similar problem. It only happens for me when the first header has only one item. If the first header contains 2+ items, the header gets pushed up correctly. Also seems like it only happens with the latest 0.5.1 snapshot.

**Comment by acatinon** [comment]
This issue is fixed in thee latest snaphot.

**Comment by vincentbrison** [comment]
Works fine, indeed, thanks ;)
