### ISSUE TITLE
Problem with GridLayoutManager

### ISSUE THREAD

**Issue by lexerptz** [eowise/recyclerview-stickyheaders#27]
When i try to use GridLayoutManager instead LinearLayoutManager all items look awful. I have not found   information about support GridLayoutManager. Is it my problem or lib bug?
![s50116-174047](https://cloud.githubusercontent.com/assets/2855590/5777819/01ae0ff2-9da7-11e4-8193-bdd3d678ab0e.jpg)

**Comment by acatinon** [comment]
Only LinearLayoutManager is supported for now. I'm not sure if is is possible to have sticky header on GridLayoutManager only with a ItemDecoration.
