### ISSUE TITLE
Is it possible to add OnHeaderScrolled event?

### ISSUE THREAD

**Issue by ravidsrk** [eowise/recyclerview-stickyheaders#28]
How do i add  an callback event OnHeaderScrolled ?

**Comment by leruaa** [comment]
You mean when you swipe an header right or left ?

**Comment by ravidsrk** [comment]
I mean when i scroll up of the recyclerview. Assuming we have setSticky(true), Header scrolls up and new header sticks to top.

**Comment by leruaa** [comment]
Currently, the only event supported on headers is Click. By the way, RecyclerView has scroll abilites. Maybe you can achieve what you want with it ?
