### ISSUE TITLE
Warnings when building project

### ISSUE THREAD

**Issue by Sandrichka22** [eowise/recyclerview-stickyheaders#35]
Hi, I have an issue when using your library. 
When I try to build my project with the command 'gradle build', I get the following warnings:

Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1: can't find referenced method 'android.support.v7.widget.RecyclerView access$100(com.eowise.recyclerview.stickyheaders.HeaderStore)' in program class com.eowise.recyclerview.stickyheaders.HeaderStore
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced method 'java.util.HashMap access$000(com.eowise.recyclerview.stickyheaders.HeaderStore)' in program class com.eowise.recyclerview.stickyheaders.HeaderStore
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: com.eowise.recyclerview.stickyheaders.HeaderStore$1$1: can't find referenced class com.eowise.recyclerview.stickyheaders.HeaderInfo
Warning: there were 7 unresolved references to classes or interfaces.

I am using the library this way:

dependencies {
    compile 'com.eowise:recyclerview-stickyheaders:0.5.1@aar'
}

So my project build fails with this exception:

FAILURE: Build failed with an exception.

java.io.IOException: Please correct the above warnings first.

Do you know what might be the problem? 
Thank you very much in advance

**Comment by leruaa** [comment]
I have no idea... Are you using an annotation processor ?

**Comment by Sandrichka22** [comment]
No, I am not.

**Comment by leruaa** [comment]
Is proguard enabled ?

**Comment by Sandrichka22** [comment]
Yes proguard is enabled, and it is a must for my project.

**Comment by leruaa** [comment]
Is the build failling when disabling proguard ?

**Comment by Sandrichka22** [comment]
When proguard is disabled, the build is successful.

**Comment by leruaa** [comment]
Can you try with :

``` groovy
dependencies {
  compile 'com.eowise:recyclerview-stickyheaders:0.5.2-SNAPSHOT@aar'
}
```

and proguard enabled ?

**Comment by Sandrichka22** [comment]
Just tried it. Using this shapshot version, my build passed as successful! Will you make an update? 
Thank you very much for the help and time.

**Comment by leruaa** [comment]
Yes, I will make an update tonight.

**Comment by Sandrichka22** [comment]
Ok, thank you once again.
