### ISSUE TITLE
Add mavenrepo/gradle support

### ISSUE THREAD

**Issue by csbenz** [eowise/recyclerview-stickyheaders#36]
Category "Enhancement", thanks :)

**Comment by leruaa** [comment]
It is already supported, please see : http://eowise.github.io/recyclerview-stickyheaders/install.html

**Comment by csbenz** [comment]
Wow, great! It should be added to the README because I have no idea how I would have found that page. Thanks!

**Comment by AndroidDeveloperLB** [comment]
Link is dead. Can you please add the instructions on the readme file?
