### ISSUE TITLE
Calendar Day Headers

### ISSUE THREAD

**Issue by HirogaKatageri** [eowise/recyclerview-stickyheaders#42]
![possible](https://cloud.githubusercontent.com/assets/8166484/6479470/b26f000a-c280-11e4-978e-33163965f16e.jpg)
I've been trying to use your library in order to create the picture above. Is it possible? How should I do it? I've failed miserably in order to create it.

**Comment by leruaa** [comment]
You can look at the sources, there is a sample application that will help you.

**Comment by HirogaKatageri** [comment]
Actually I did take a look at the sample application, and I've followed most of it, it shows my data properly but... It doesn't show the header. Is there anything I'm missing?
![1](https://cloud.githubusercontent.com/assets/8166484/6480435/b242e782-c28e-11e4-8c09-af9b8055f757.jpg)
![2](https://cloud.githubusercontent.com/assets/8166484/6480436/b24a6fa2-c28e-11e4-9670-21b1dafc616b.jpg)
![3](https://cloud.githubusercontent.com/assets/8166484/6480437/b24ea202-c28e-11e4-8ac9-b5b3475bb459.jpg)

**Comment by leruaa** [comment]
Why are you instantiating two VconEventAdapter ? I'm not sure if it is related, but exept that, I don't see what's wrong.

**Comment by HirogaKatageri** [comment]
Uhh... my bad I forgot I could instantiate just one of them thanks for that xD... Anyways it's still the same though... I checked logs and it retrieves the day. It just somehow doesn't set the header... In your sample app how does it check the first two letter in every holder and compare it to the other holders?
![1](https://cloud.githubusercontent.com/assets/8166484/6481764/37e3b568-c29b-11e4-88c2-4cca9979a41b.jpg)

**Comment by leruaa** [comment]
Is there a chance that the headers text is white ?

**Comment by HirogaKatageri** [comment]
I never thought of that... LOL and yeah now it's showing the header. I'm terribly sorry X_X. Now I just need to set up the header to display in the first entry and I'll be done, really thanks though xD

**Comment by Hiroga527** [comment]
Um... help again please if it's alright... My current problem is well I am able to display the header at the first entry but it won't stick to the others that has the same day on them.


![1](https://cloud.githubusercontent.com/assets/8166484/6499514/ac44e35e-c337-11e4-98f8-40a0bbc965a3.jpg)
![2](https://cloud.githubusercontent.com/assets/8166484/6499515/ac497982-c337-11e4-87d4-92a3eaf58c80.jpg)
![3](https://cloud.githubusercontent.com/assets/8166484/6499516/ac53a48e-c337-11e4-97cb-f5913c991d1e.jpg)

**Comment by HirogaKatageri** [comment]
Um... help again please if it's alright... My current problem is well I am able to display the header at the first entry but it won't stick to the others that has the same day on them.

This is my code to take out duplicate header texts since it shows the header on each view.
I'm trying to figure out how the header will stick till the last related view or make the header in the other related views be invisible in the beginning and as you scroll and it becomes the first one seen it'll be visible.

```
if (position == 0 || Event.EventList[position - 1].day != (Event.EventList[position].day)) {
    viewHolder.dayHeader.setText(day);
}
```

![1](https://cloud.githubusercontent.com/assets/8166484/6499514/ac44e35e-c337-11e4-98f8-40a0bbc965a3.jpg)
![2](https://cloud.githubusercontent.com/assets/8166484/6499515/ac497982-c337-11e4-87d4-92a3eaf58c80.jpg)
![3](https://cloud.githubusercontent.com/assets/8166484/6499516/ac53a48e-c337-11e4-97cb-f5913c991d1e.jpg)

**Comment by HirogaKatageri** [comment]
Um... Nvm I got it already. I needed to set the get header ID to the day instead of a hashcode.
